export enum ErrorCode {
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  DUPLICATE_PHONE_NUMBER = 'DUPLICATE_PHONE_NUMBER',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  INVALID_OTP = 'INVALID_OTP',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  INVALID_REFRESH_TOKEN = 'INVALID_REFRESH_TOKEN',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
}
