export const INJECTION_TOKENS = {
  REDIS_CLIENT: Symbol('REDIS_CLIENT'),
  USER_REPOSITORY: Symbol('USER_REPOSITORY'),
  SMS_SERVICE: Symbol('SMS_SERVICE'),
  REQUEST_REPOSITORY: Symbol('REQUEST_REPOSITORY'),
  TRANSCRIBE_REPOSITORY: Symbol('TRANSCRIBE_REPOSITORY'),
  WALLET_REPOSITORY: Symbol("WALLET_REPOSITORY"),
   WALLET_TRANSACTION_REPOSITORY: Symbol("WALLET_TRANSACTION_REPOSITORY"),
   API_KEY_REPOSITORY: Symbol("API_KEY_REPOSITORY")
} as const;
