export const INJECTION_TOKENS = {
  REDIS_CLIENT: Symbol('REDIS_CLIENT'),
  USER_REPOSITORY: Symbol('USER_REPOSITORY'),
  SMS_SERVICE: Symbol('SMS_SERVICE'),
  DASHBORD_REPOSITORY: Symbol('DASHBORD_REPOSITORY'),
  WALLET_REPOSITORY: Symbol("WALLET_REPOSITORY")
} as const;
